include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoDCCP/dccp
GOFILES=\
	label.go\
	muxmsg.go\
	mux.go\
	flow.go\
	checksum.go\
	header.go\
	header-util.go\
	read.go\
	options.go\
	wire.go\
	write.go\
	addr.go\
	link.go\
	udplink.go\
	chanlink.go\
	signal.go\
	servicecode.go\
	block.go\
	err.go\
	socket.go\
	conn.go\
	conn-inject.go\
	conn-process.go\
	conn-seqack.go\
	backoff.go\
	#dccp.go\
	#switch.go\
	#dial.go\
	#listener.go\
	#endlogic.go\
	#endlogic-loop.go
	#conn.go\
	#header-util.go\
	#congestion.go\
	#timing.go\

include $(GOROOT)/src/Make.pkg
