include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoDCCP/dccp
GOFILES=\
	addr.go\
	backoff.go\
	block.go\
	cc.go\
	ccconst.go\
	ccid3.go\
	ccid3opt.go\
	chanlink.go\
	checksum.go\
	conn.go\
	conndbg.go\
	conngen.go\
	conngoto.go\
	conninj.go\
	connpipe.go\
	connseqack.go\
	connsteps.go\
	connterm.go\
	connuser.go\
	ctrlc.go\
	dccp.go\
	dial.go\
	err.go\
	flow.go\
	header.go\
	headerutil.go\
	label.go\
	link.go\
	listener.go\
	mutex.go\
	mux.go\
	muxmsg.go\
	options.go\
	read.go\
	servicecode.go\
	socket.go\
	string.go\
	timeopt.go\
	udplink.go\
	wire.go\
	write.go\

include $(GOROOT)/src/Make.pkg
