#!/bin/sh
pushd ./
rm log
setenv DCCPD3 dccp.d3
make clean && make install \
	&& cd gauge && make clean && make install \
	&& cd ../ccid3 && make clean && make install \
	&& cd ../sandbox && make clean && make install \
	&& gotest
popd
