#!/bin/sh
pushd ./
rm log
make clean && make install \
	&& cd gauge && make clean && make install \
	&& cd inspector && make clean && make install \
	&& cd ../../ccid3 && make clean && make install \
	&& cd ../sandbox && make clean && make install \
	&& cd openclose && make clean && make install \
	&& ./openclose
popd
