#!/bin/sh
pushd ./
rm log
make clean && make install \
	&& cd gauge && make clean && make install \
	&& cd ../ccid3 && make clean && make install \
	&& cd ../sandbox && make clean && make install \
	&& gotest -test.cpuprofile=cpu.out
popd
