// Copyright 2010 GoDCCP Authors. All rights reserved.
// Use of this source code is governed by a 
// license that can be found in the LICENSE file.

package retransmit

// All sequence numbers are uint32 circular integers

type header struct {
	data *dataHeader
	ack  *ackHeader
}

// Sender-to-receiver half-connection subheader
type dataHeader struct {

	// DataNo is the sequence Number of the data block
	DataNo uint32

	// Contents of the data block
	Data []byte

	// Sync indicates that the sender is requesting an ack packet
	Sync bool

	// SyncNo is the sequence number of the sync request, generated by the sender
	SyncNo uint32
}

// Receiver-to-sender half-connection subheader
//
// The ackHeader should be sent when either:
// (*) duplicate data has been received,
// (*) Sync has been received
type ackHeader struct {

	// SyncAckNo is the SyncNo this acknowledgement is in response to
	SyncAckNo uint32
	
	// DataAckNo is the sequence number of the first block in the acknowledgements map.
	// This number also indicates that all data blocks with sequence numbers lower 
	// than DataAckNo have already been received.
	DataAckNo uint32

	// AckMap is a bitmap where 1's correspond to blocks that HAVE been received
	AckMap []byte
}
