include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoDCCP/dccp/ccid3
GOFILES=\
	loss.go\
	opts.go\

	#ccid3.go\
	#receiver.go\
	#receiverate.go\
	#rtt.go\
	#sender.go\
	#strober.go\
	#windowcounter.go\

include $(GOROOT)/src/Make.pkg
