include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoDCCP/dccp/ccid3
GOFILES=\
	ccid3.go\
	loss.go\
	opts.go\
	receiver.go\
	receiverate.go\
	rtt.go\
	sender.go\
	strober.go\
	windowcounter.go\

include $(GOROOT)/src/Make.pkg
