include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoDCCP/dccp/ccid3
GOFILES=\
	err.go\
	interval.go\
	loss.go\
	nofeedback.go\
	opts.go\
	rate.go\
	receiver.go\
	rtt.go\
	table.go\
	track.go\
	strober.go\
	windowcounter.go\
	ss.go\
	util.go\
	x.go\
	sender.go\
	ccid3.go\

include $(GOROOT)/src/Make.pkg
